### PR TITLE
Refactor usages

### PR DESCRIPTION
**Pull request by owarai**
refactor and add usages like sdk-java cause user complains about the usage example shortage.

### CODE REVIEW

**Comment by owarai** [comment]
Chinese and English docs added. With structure like official qingstor api docs.
Also README.md is slightly modified.

**Review by Xuanwo — APPROVED** [review]
~~deleted~~

**Review by Xuanwo — CHANGES_REQUESTED** [review]
Use `README_zh-CN.md` instead to fit ISO standard, and same for all following docs.

ref:

- en.wikipedia.org/wiki/List_of_ISO_639-1_codes
- en.wikipedia.org/wiki/Language_localisation

**Comment by owarai** [comment]
resolved.

**Pull request merged**
